INCLUDE(ExternalProject)

message("CMAKE_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX}")
ExternalProject_Add(
    EasyCL-external
    SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/EasyCL
    PREFIX ${CMAKE_BINARY_DIR}/EasyCL
    INSTALL_DIR ${CMAKE_INSTALL_PREFIX}
    STAMP_DIR ${CMAKE_BINARY_DIR}/EasyCL/stamp
    CMAKE_CACHE_ARGS 
    -DCMAKE_INSTALL_PREFIX:PATH=${CMAKE_INSTALL_PREFIX}
    -DBUILD_SHARED_LIBRARY:BOOL=ON
    -DBUILD_TESTS:BOOL=OFF
    -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo
    )

ADD_LIBRARY(EasyCL SHARED IMPORTED)
SET_PROPERTY(TARGET EasyCL PROPERTY IMPORTED_LOCATION "${CMAKE_INSTALL_PREFIX}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}EasyCL${CMAKE_SHARED_LIBRARY_SUFFIX}")
SET_PROPERTY(TARGET EasyCL PROPERTY IMPORTED_IMPLIB "${CMAKE_INSTALL_PREFIX}/lib/EasyCL.lib")
ADD_DEPENDENCIES(EasyCL EasyCL-external)
SET(EASYCL_INCLUDE_DIRS ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/EasyCL/include)
#message("lib path ${CMAKE_INSTALL_PREFIX}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}EasyCL${CMAKE_SHARED_LIBRARY_SUFFIX}")
SET(EASYCL_LIBRARIES ${CMAKE_INSTALL_PREFIX}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}EasyCL${CMAKE_SHARED_LIBRARY_SUFFIX})
SET(EASYCL_FOUND ON)

#add_custom_target(EasyCL_delete_stamp EasyCL-external clBLAS-external
#  ${CMAKE_COMMAND} -E  remove_directory "${CMAKE_BINARY_DIR}/EasyCL/stamp"
#)

